version: '3.8'

services:
  ctf-challenge:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: makhal-auth-bypass
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    cap_add:
      - NET_BIND_SERVICE
    read_only: true
    tmpfs:
      - /tmp
      - /var/run/apache2
    volumes:
      - ./src:/var/www/html:ro
    networks:
      - frontend
    labels:
      - "traefik.enable=true"
      # HTTP -> HTTPS redirection
      - "traefik.http.routers.ctf-challenge.entrypoints=http"
      - "traefik.http.routers.ctf-challenge.rule=Host(`ctf.makhal.fr`)"
      - "traefik.http.routers.ctf-challenge.middlewares=https-redirect"
      - "traefik.http.middlewares.https-redirect.redirectscheme.scheme=https"
      # HTTPS configuration
      - "traefik.http.routers.ctf-challenge-secure.entrypoints=https"
      - "traefik.http.routers.ctf-challenge-secure.rule=Host(`ctf.makhal.fr`)"
      - "traefik.http.routers.ctf-challenge-secure.tls=true"
      - "traefik.http.routers.ctf-challenge-secure.tls.certresolver=cloudflare"
      # Security headers middleware
      - "traefik.http.middlewares.security-headers.headers.browserXssFilter=true"
      - "traefik.http.middlewares.security-headers.headers.contentTypeNosniff=true"
      - "traefik.http.middlewares.security-headers.headers.forceSTSHeader=true"
      - "traefik.http.middlewares.security-headers.headers.stsIncludeSubdomains=true"
      - "traefik.http.middlewares.security-headers.headers.stsPreload=true"
      - "traefik.http.middlewares.security-headers.headers.stsSeconds=31536000"
      - "traefik.http.middlewares.security-headers.headers.customFrameOptionsValue=DENY"
      - "traefik.http.routers.ctf-challenge-secure.middlewares=security-headers"
      # Rate limiting to prevent brute forcing
      - "traefik.http.middlewares.ctf-rate-limit.ratelimit.average=3"
      - "traefik.http.middlewares.ctf-rate-limit.ratelimit.burst=5"
      - "traefik.http.routers.ctf-challenge-secure.middlewares=ctf-rate-limit,security-headers"
      # Service configuration
      - "traefik.http.services.ctf-service.loadbalancer.server.port=80"
      - "traefik.http.routers.ctf-challenge-secure.service=ctf-service"

networks:
  frontend:
    external: true
